const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');
const { writeFile } = require('node:fs/promises');
const { join } = require('node:path');
const { tmpdir } = require('node:os');
const { PrismaService } = require('./dist/prisma/prisma.service');
const { QuotesService } = require('./dist/quotes/quotes.service');
const { BillingService } = require('./dist/billing/billing.service');
const { ServiceOrdersService } = require('./dist/service-orders/service-orders.service');
const { atomic } = require('./dist/workflow/transaction');
const { issueItem } = require('./dist/workflow/stock');
const { mediaLink, verifyMediaLink } = require('./dist/media/media-links');
const { MediaService } = require('./dist/media/media.service');
const url = new URL(process.env.DATABASE_URL);
if (process.env.NODE_ENV !== 'test' || !['localhost','127.0.0.1'].includes(url.hostname) || url.pathname !== '/tamir_bakim') throw new Error('Only disposable localhost test database allowed');
const db = new PrismaService();
(async () => {
 await db.$connect();
 const org = await db.organization.create({ data: { name: `Workflow regression ${randomUUID()}` } });
 const organizationId = org.id;
 const branch = await db.branch.create({ data: { organizationId, name: 'Test' } });
 const branchId = branch.id;
 const customer = await db.customer.create({ data: { organizationId, branchId, firstName: 'Test' } });
 const vehicle = await db.vehicle.create({ data: { organizationId, branchId, customerId: customer.id, plate: randomUUID(), brand: 'Test', model: 'Test' } });
 const tech = await db.user.create({ data: { organizationId, branchId, firstName: 'Test', lastName: 'Tech', email: `${randomUUID()}@example.invalid`, passwordHash: 'unused', role: 'TECHNICIAN' } });
 const order = await db.serviceOrder.create({ data: { organizationId, branchId, customerId: customer.id, vehicleId: vehicle.id, mileage: 50000, orderNumber: randomUUID(), assignedTechnicianId: tech.id,
 items: { create: { name: 'Bakım', type: 'LABOR', quantity: 1, unitPrice: 0, totalPrice: 0 } } }, include: { items: true } });
 const quotes = new QuotesService(db), billing = new BillingService(db), orders = new ServiceOrdersService(db);
 const quote = await quotes.create(organizationId, branchId, 'OWNER', { customerId: customer.id, vehicleId: vehicle.id, serviceOrderId: order.id,
 items: [{ serviceOrderItemId: order.items[0].id, name: 'Bakım', type: 'LABOR', quantity: 1, unitPrice: 100, vatRate: 20 }] });
 await quotes.updateStatus(organizationId, quote.id, 'APPROVED', 'OWNER', branchId);
 let current = await db.serviceOrder.findUnique({ where: { id: order.id }, include: { items: true } });
 assert.equal(current.items.length,1); assert.equal(current.items[0].id,order.items[0].id); assert.equal(Number(current.items[0].grossTotal),120);
 await orders.updateStatus(organizationId,order.id,'IN_PROGRESS','TECHNICIAN',tech.id,branchId);
 await quotes.updateStatus(organizationId,quote.id,'APPROVED','OWNER',branchId);
 assert.equal((await db.serviceOrder.findUnique({where:{id:order.id}})).status,'IN_PROGRESS');
 await assert.rejects(orders.updateStatus(organizationId,order.id,'READY','TECHNICIAN',tech.id,branchId));
 const payment = { customerId: customer.id, serviceOrderId: order.id, quoteId: quote.id, amount: 80, method: 'CASH', requestKey: randomUUID() };
 const results = await Promise.allSettled([billing.create(organizationId,branchId,'ACCOUNTING',payment), billing.create(organizationId,branchId,'ACCOUNTING',{...payment,requestKey:randomUUID()})]);
 assert.equal(results.filter(r=>r.status==='fulfilled').length,1,'Concurrent overpayment prevented');
 const successful = results.find(r=>r.status==='fulfilled').value;
 const retryKey = successful.requestKey;
 assert.equal((await billing.create(organizationId,branchId,'ACCOUNTING',{...payment,requestKey:retryKey})).id,successful.id);
 let pending = await db.payment.findMany({where:{quoteId:quote.id,status:'PENDING'}}); assert.equal(pending.length,1);assert.equal(Number(pending[0].amount),40);
 const plan = await db.maintenancePlan.create({data:{organizationId,branchId,vehicleId:vehicle.id,title:'Yağ bakımı',intervalKm:10000,intervalMonths:12,nextDueKm:50000}});
 await orders.linkMaintenancePlans(organizationId,order.id,'OWNER',tech.id,branchId,[plan.id]);
 await orders.setItemComplete(organizationId,order.id,order.items[0].id,'TECHNICIAN',tech.id,branchId,true);
 await orders.updateStatus(organizationId,order.id,'READY','TECHNICIAN',tech.id,branchId);
 await assert.rejects(orders.updateStatus(organizationId,order.id,'DELIVERED','ACCOUNTING',tech.id,branchId));
 await billing.create(organizationId,branchId,'ACCOUNTING',{...payment,amount:40,requestKey:randomUUID()});
 assert.equal(await db.payment.count({where:{quoteId:quote.id,status:'PENDING'}}),0);
 await orders.updateStatus(organizationId,order.id,'DELIVERED','ACCOUNTING',tech.id,branchId);
 assert.equal(await db.maintenanceRecord.count({where:{serviceOrderId:order.id}}),1);
 assert.equal((await db.maintenancePlan.findUnique({where:{id:plan.id}})).status,'COMPLETED');
 const renewed = await db.maintenancePlan.findFirst({where:{vehicleId:vehicle.id,status:'ACTIVE',lastKm:50000}});
 assert.equal(renewed.nextDueKm,60000);
 await orders.updateStatus(organizationId,order.id,'DELIVERED','ACCOUNTING',tech.id,branchId);
 assert.equal(await db.maintenanceRecord.count({where:{serviceOrderId:order.id}}),1);
 const part = await db.part.create({data:{organizationId,name:'Filter',sku:randomUUID()}});
 await db.inventory.create({data:{organizationId,branchId,partId:part.id,quantity:1}});
 const stockItems = await Promise.all([0,1].map(async i=>db.serviceOrderItem.create({data:{serviceOrderId:order.id,partId:part.id,name:`Filter ${i}`,type:'PART',quantity:1,unitPrice:1,totalPrice:1}})));
 const stock = await Promise.allSettled(stockItems.map(item=>atomic(db,organizationId,tx=>issueItem(tx,organizationId,branchId,item,tech.id))));
 assert.equal(stock.filter(r=>r.status==='fulfilled').length,1);assert.equal(Number((await db.inventory.findFirst({where:{partId:part.id}})).quantity),0);
 const link = mediaLink('file',{organizationId,sub:tech.id,role:'TECHNICIAN'}); const access = new URL(link,'https://example.invalid/').searchParams.get('access');
 assert.equal(verifyMediaLink('file',access).org,organizationId);assert.throws(()=>verifyMediaLink('other',access));assert.throws(()=>verifyMediaLink('file',access+'x'));
 const path = join(tmpdir(), `workflow-media-${randomUUID()}.jpg`); await writeFile(path,Buffer.from('persistent-private-photo'));
 const mediaService = new MediaService(db); const media = await mediaService.create(organizationId,branchId,'TECHNICIAN',tech.id,
   {type:'AFTER',serviceOrderId:order.id,vehicleId:vehicle.id,requestKey:randomUUID(),customerVisible:'false'},
   {path,filename:`${randomUUID()}.jpg`,originalname:'test.jpg',mimetype:'image/jpeg',size:24});
 assert.equal(await db.mediaObject.count({where:{mediaId:media.id}}),1);
 const mediaAccess = new URL(mediaLink(media.id,{organizationId,sub:tech.id,role:'TECHNICIAN',tokenVersion:0}),'https://example.invalid/').searchParams.get('access');
 const content = await mediaService.readContent(media.id,mediaAccess); assert.equal(Buffer.from(content.body).toString(),'persistent-private-photo');
 console.log('PASS: quote identity/reapproval, transition gates, concurrent payments/retries/balances, completion/delivery/history/plan renewal, concurrent stock, persistent signed media isolation.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>db.$disconnect());
